### ISSUE TITLE
Can't make it run

### ISSUE THREAD

**Issue by sgandon** [kubernetes-csi/csi-driver-image-populator#10]
I have deployed the manifest in the `/deploy/image` folder.
It seems there is not need to build any image cause it is refering to a quay.io remote image anyway.
I have tried to deploy this pod.
```apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - name: main
    image: busybox
    command: [ "sleep", "1000000" ]
    volumeMounts:
    - name: data
      mountPath: /var/www/html
  volumes:  
  - name: data
    csi:
      driver: image.csi.k8s.io
      volumeAttributes:
        image: busybox
```
But it fails with the following errors
```The Pod "test" is invalid:
* spec.volumes[0]: Required value: must specify a volume type
* spec.containers[0].volumeMounts[0].name: Not found: "data"
```
Am I doing something wrong ? do I need more things in my setup ? (I am using the docker-for-desktop on mac kubernetes cluster)
Is this project just to old and not maintained ?

**Comment by catto** [comment]
@sgandon I've seen the same error before. The cause was that I forgot to set `--feature-gates=CSIInlineVolume` to kubelet, just did it only to apiserver. It has been resolved by adding the option to kubelet.

**Comment by sgandon** [comment]
Ok so what you say is that you need to enable this feature in the feature gate. It seems not possible with docker for desktop (see https://github.com/docker/for-mac/issues/2382).
I'll try on minikube then.

**Comment by sgandon** [comment]
launching it with minikube with the following arguments works
```
minikube start --vm-driver hyperkit --cpus 4 --memory 10000 --feature-gates CSIInlineVolume=true --kubernetes-version v1.15.4```
Thanks for the explanation.

**Comment by sgandon** [comment]
We have such requirement to mount a docker image for our production workload, is there any plan that this driver be production ready ?
thanks.
