### ISSUE TITLE
Brief architectural overview

### ISSUE THREAD

**Issue by fizzyduck** [kubernetes-csi/csi-driver-image-populator#14]
Hi,

Would you mind providing a brief overview of how this plugin works in the readme.md? I would like to better understand how the storage (from the Docker image) is attached to the volume.

Kind regards.

**Comment by kfox1111** [comment]
Sorry. I missed watching the repo so missed your question.

The readme mentions that it calls buildah to do the work. Are you wanting to know more about how buildah works, or how the mounts between buildah and k8s work?
