### ISSUE TITLE
Remove reference to gocsi

### ISSUE THREAD

**Issue by xing-yang** [kubernetes-csi/csi-driver-image-populator#17]
Reference to gocsi should be removed from README as gocsi is no longer maintained:

https://github.com/kubernetes-csi/csi-driver-image-populator#test-using-csc

**Comment by f10atin9** [comment]
This issue can be closed. @xing-yang

**Comment by f10atin9** [comment]
It fixed by #18

**Comment by f10atin9** [comment]
/cc @kfox1111 
This issue already fixed by #18 . Can you close it?
Thanks :)
