### ISSUE TITLE
Setup release infra

### ISSUE THREAD

**Issue by msau42** [kubernetes-csi/csi-driver-image-populator#2]
@pohly can you help with this?

**Comment by msau42** [comment]
I will work on enabling travis and quay
/assign

**Comment by pohly** [comment]
See https://github.com/kubernetes-csi/csi-driver-image-populator/pull/3

**Comment by kfox1111** [comment]
Looks like this is next up? Anything I can help with?

**Comment by msau42** [comment]
quay and travis should be setup already, but it looks like the latest run didn't push anything

**Comment by pohly** [comment]
https://travis-ci.org/kubernetes-csi/csi-driver-image-populator/builds/519479148:
```
....
The push refers to a repository [quay.io/k8scsi/imageplugin]
ee49afc8beef: Preparing
52441e9e9fd4: Preparing
d69483a6face: Preparing
unauthorized: access to the requested resource is not authorized
make: *** [push-imageplugin] Error 1
```
