### ISSUE TITLE
master branch can not run "build image"

### ISSUE THREAD

**Issue by zhengchao88** [kubernetes-csi/csi-driver-image-populator#7]
I fetch code from master branch, when running "build image", below error occurs.
_make: *** No rule to make target `image'.  Stop._

With changing the command to "make", still got error.
_mkdir -p bin
CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-X main.version=144ad7194d9cbc451cfe094331d1b80bab53cfdd -extldflags "-static"' -o ./bin/imagepopulatorplugin ./cmd/imagepopulatorplugin
cmd/imagepopulatorplugin/main.go:23:2: cannot find package "github.com/kubernetes-csi/csi-driver-image-populator/pkg/image" in any of:
	/usr/lib/golang/src/github.com/kubernetes-csi/csi-driver-image-populator/pkg/image (from $GOROOT)
	/root/go/src/github.com/kubernetes-csi/csi-driver-image-populator/pkg/image (from $GOPATH)
make: *** [build-imagepopulatorplugin] Error 1_

**Comment by sgandon** [comment]
same here, I'd like to test this driver but can't build it.

**Comment by sgandon** [comment]
@zhengchao88 But if you move the folder to 
`/root/go/src/github.com/kubernetes-csi/csi-driver-image-populator/`
the make should work.
